diaspora-develop/diaspora-develop/config/routes.rb
# frozen_string_literal: true

#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require "sidekiq/web"
require "sidekiq/cron/web"
Sidekiq::Web.set :sessions, false # disable rack session cookie

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :report, except: %i(edit new show)

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]

  resources :posts, only: %i(show destroy) do
    member do
      get :mentionable
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
    resources :reshares, only: :index
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  get "link" => "links#resolve"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
    get "raw"
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end


  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
    post :auth_token
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

  resource :two_factor_authentication, only: %i[show create destroy] do
    get :confirm, action: :confirm_2fa
    post :confirm, action: :confirm_and_activate_2fa
    get :recovery_codes
  end

  devise_for :users, controllers: {sessions: :sessions}, skip: :registration
  devise_scope :user do
    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
    post "/users"        => "registrations#create", :as => :user_registration
    get "/registrations_closed" => "registrations#registrations_closed", :as => :registrations_closed
  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
    post 'users/:id/make_admin' => 'users#make_admin', :as => 'make_admin'
    post 'users/:id/remove_admin' => 'users#remove_admin', :as => 'remove_admin'
    post 'users/:id/make_moderator' => 'users#make_moderator', :as => 'make_moderator'
    post 'users/:id/remove_moderator' => 'users#remove_moderator', :as => 'remove_moderator'
    post 'users/:id/make_spotlight' => 'users#make_spotlight', :as => 'make_spotlight'
    post 'users/:id/remove_spotlight' => 'users#remove_spotlight', :as => 'remove_spotlight'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
  root :to => 'home#show'
  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
  get "manifest.json", to: "manifest#show"
end

diaspora-develop/diaspora-develop/app/controllers/streams_controller.rb
# frozen_string_literal: true

#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class StreamsController < ApplicationController
  before_action :authenticate_user!, except: :public
  before_action :save_selected_aspects, :only => :aspects

  layout proc { request.format == :mobile ? "application" : "with_header" }

  respond_to :html,
             :mobile,
             :json

  def aspects
    aspect_ids = (session[:a_ids] || [])
    @stream = Stream::Aspect.new(current_user, aspect_ids,
                                 :max_time => max_time)
    stream_responder
  end

  def public
    stream_responder(Stream::Public)
  end

  def activity
    stream_responder(Stream::Activity)
  end

  def multi
    if current_user.getting_started
      gon.preloads[:getting_started] = true
      inviter = current_user.invited_by.try(:person)
      gon.preloads[:mentioned_person] = {name: inviter.name, handle: inviter.diaspora_handle} if inviter
    end

    stream_responder(Stream::Multi)
  end

  def commented
    stream_responder(Stream::Comments)
  end

  def liked
    stream_responder(Stream::Likes)
  end

  def mentioned
    stream_responder(Stream::Mention)
  end

  def followed_tags
    gon.preloads[:tagFollowings] = tags
    stream_responder(Stream::FollowedTag)
  end

  private

  def stream_responder(stream_klass=nil)

    if stream_klass.present?
      @stream ||= stream_klass.new(current_user, :max_time => max_time)
    end

    respond_with do |format|
      format.html { render 'streams/main_stream' }
      format.mobile { render 'streams/main_stream' }
      format.json { render :json => @stream.stream_posts.map {|p| LastThreeCommentsDecorator.new(PostPresenter.new(p, current_user)) }}
    end
  end

  def save_selected_aspects
    if params[:a_ids].present?
      session[:a_ids] = params[:a_ids]
    end
  end
end

diaspora-develop/diaspora-develop/app/helpers/stream_helper.rb
# frozen_string_literal: true

#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module StreamHelper
  def next_page_path(opts ={})
    if controller.instance_of?(TagsController)
      tag_path(:name => @stream.tag_name, :max_time => time_for_scroll(@stream))
    elsif controller.instance_of?(PeopleController)
      local_or_remote_person_path(@person, :max_time => time_for_scroll(@stream))
    elsif controller.instance_of?(StreamsController)
      next_stream_path
    else
      raise 'in order to use pagination for this new controller, update next_page_path in stream helper'
    end
  end

  def reshare?(post)
    post.instance_of?(Reshare)
  end

  private

  def next_stream_path
    if current_page?(:stream)
      stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:activity_stream)
      activity_stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:aspects_stream)
      aspects_stream_path(max_time: time_for_scroll(@stream), a_ids: session[:a_ids])
    elsif current_page?(:public_stream)
      public_stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:commented_stream)
      commented_stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:liked_stream)
      liked_stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:mentioned_stream)
      mentioned_stream_path(max_time: time_for_scroll(@stream))
    elsif current_page?(:followed_tags_stream)
      followed_tags_stream_path(max_time: time_for_scroll(@stream))
    else
      raise "in order to use pagination for this new stream, update next_stream_path in stream helper"
    end
  end

  def time_for_scroll(stream)
    if stream.stream_posts.empty?
      (Time.now() + 1).to_i
    else
      stream.stream_posts.last.send(stream.order.to_sym).to_i
    end
  end
end

diaspora-develop/diaspora-develop/app/views/streams/main_stream.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  - if AppConfig.chat.enabled?
    = javascript_include_tag :jsxc, id: 'jsxc',
      data: { endpoint: get_bosh_endpoint }

- if current_user&.getting_started?
  #welcome-to-diaspora
    .container-fluid
      .row
        .col-md-9
          %h1
            = t('aspects.index.welcome_to_diaspora', name: current_user.first_name)
          %h3
            = t('aspects.index.introduce_yourself')
        .col-md-3
          .pull-right
            = link_to '&times;'.html_safe, getting_started_completed_path, id: "gs-skip-x", class: "close"

.container-fluid
  .row
    - if user_signed_in?
      .col-md-3
        .sidebar.left-navbar
          %ul#stream-selection
            %li{data: {stream: "stream"}}
              = link_to t("streams.multi.title"), stream_path, rel: "backbone", class: "hoverable"
            %li.nested-list.my-activity{data: {stream: "activity"}}
              = link_to t("streams.activity.title"), activity_stream_path, rel: "backbone", class: "hoverable"
              %ul
                %li{data: {stream: "liked"}}
                  = link_to t("streams.liked.title"), liked_stream_path, rel: "backbone", class: "hoverable selectable"
                %li{data: {stream: "commented"}}
                  = link_to t("streams.commented.title"), commented_stream_path,
                    rel: "backbone", class: "hoverable selectable"
            %li{data: {stream: "mentions"}}
              = link_to t("streams.mentions.title"), mentioned_stream_path, rel: "backbone", class: "hoverable"
            %li.nested-list.all-aspects
              = render "aspects/aspect_listings", stream: @stream
            %li.nested-list
              = render "tags/followed_tags_listings"
            %li{data: {stream: "public"}}
              = link_to t("streams.public.title"), public_stream_path, rel: "backbone", class: "hoverable"

        .sidebar.info-bar.hidden-xs
          - if AppConfig.settings.invitations.open?
            .section.collapsed
              .title
                %h5.title-header
                  .entypo-triangle-right
                  .entypo-triangle-down
                  = t("shared.invitations.invite_your_friends")
              .content
                = render "shared/invitations"

          .section.collapsed
            .title
              %h5.title-header
                .entypo-triangle-right
                .entypo-triangle-down
                = t("aspects.index.new_here.title")
            .content
              != t("aspects.index.new_here.follow",
                link: link_to("#" + t("shared.publisher.new_user_prefill.newhere"),
                tag_path(name: t("shared.publisher.new_user_prefill.newhere"))))
              %br
              = link_to(t("aspects.index.new_here.learn_more"),
                "http://wiki.diasporafoundation.org/Welcoming_Committee")

          .section.collapsed
            .title
              %h5.title-header
                .entypo-triangle-right
                .entypo-triangle-down
                = t("aspects.index.help.need_help")
            .content
              %p
                = t("aspects.index.help.here_to_help")
              %p
                = t("aspects.index.help.do_you")
              %ul
                %li
                  != t("aspects.index.help.have_a_question",
                    link: link_to("#" + t("aspects.index.help.tag_question"),
                    tag_path(name: t("aspects.index.help.tag_question"))))
                %li
                  != t("aspects.index.help.find_a_bug",
                    link: link_to(t("aspects.index.help.tag_bug"),
                    "https://wiki.diasporafoundation.org/How_to_report_a_bug"))
                %li
                  != t("aspects.index.help.feature_suggestion",
                    link: link_to(t("aspects.index.help.tag_feature"),
                    "https://discourse.diasporafoundation.org/c/features-and-ideas"))
              %p
                != t("aspects.index.help.tutorials_and_wiki",
                  faq: link_to(t("_help"), help_path),
                  tutorial: link_to(t("aspects.index.help.tutorial_link_text"),
                    "https://diasporafoundation.org/tutorials", target: "_blank"),
                  wiki: link_to("Wiki", "http://wiki.diasporafoundation.org",
                    target: "_blank"),
                  target: "_blank")

              %p
                != t("aspects.index.help.support_forum",
                  support_forum: link_to(t("aspects.index.help.support_forum_link"),
                  "https://discourse.diasporafoundation.org/c/support", target: "_blank"))

          - unless AppConfig.configured_services.blank? || all_services_connected?
            .section.collapsed
              .title
                %h5.title-header
                  .entypo-triangle-right
                  .entypo-triangle-down
                  = t("aspects.index.services.heading")
              .content
                %div
                  = t("aspects.index.services.content")

                .right-service-icons
                  - AppConfig.configured_services.each do |service|
                    - if service_unconnected?(service)
                      = link_to(content_tag(:div, nil,
                        class: "social-media-logos-#{service.to_s.downcase}-24x24",
                        title: service.to_s.titleize), "/auth/#{service}")

          .section.collapsed
            .title
              %h5.title-header
                .entypo-triangle-right
                .entypo-triangle-down
                = t("bookmarklet.heading")
            .content
              != t("bookmarklet.explanation", link: link_to(t("bookmarklet.post_something"), bookmarklet_code))

          - if donations_enabled?
            .section.collapsed
              .title
                %h5.title-header
                  .entypo-triangle-right
                  .entypo-triangle-down
                  = t("aspects.index.donate")
              .content
                %p
                  = t("aspects.index.keep_pod_running", pod: AppConfig.pod_uri.host)
                = render "shared/donatepod"

          - if AppConfig.admins.podmin_email.present?
            .section.collapsed
              .title
                %h5.title-header
                  .entypo-triangle-right
                  .entypo-triangle-down
                  = t("aspects.index.help.any_problem")
              .content
                %p
                  = t("aspects.index.help.contact_podmin")
                %p
                  = link_to t("aspects.index.help.mail_podmin"), "mailto:#{AppConfig.admins.podmin_email}"

          .excellence-box
            .content
              %p
                = link_to t("layouts.application.be_excellent"), "https://diasporafoundation.org/community_guidelines"

          .info-links
            .content
              %ul
                = render "shared/links"

          .powered-box
            .content
              .powered-by-diaspora.text-center
                = link_to t("layouts.application.powered_by"), "https://diasporafoundation.org"

    .col-md-9{class: ("center-block public-stream" unless user_signed_in?)}
      .stream-container#aspect-stream-container
        - unless user_signed_in?
          %h2= @stream.title
        = render "aspects/aspect_stream", stream: @stream

diaspora-develop/diaspora-develop/app/views/streams/main_stream.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- unless user_signed_in?
  %h1= @stream.title

#main-stream.stream
  = render 'shared/stream', posts: @stream.stream_posts
  = render 'shared/stream_more_button'